### ISSUE TITLE
Item component

### ISSUE THREAD

**Issue by chase0213** [ngjapan-attack/nghackday2016-sagittarius#8]
### Property

- ローラースケート
- 持てる爆弾を増やせるやつ
- 投げられる奴
- 壁すり抜けられる奴
- けれる奴
- 威力増減するやつ

[ 1 0 0 0 0 0 0 ]
[ -1 0 0 0 0 0 0 ]
[ 0 1 0 0 0 0 0 0 ]

**Comment by chohey** [comment]
**ベクター案はなし** にして、上記それぞれを _number_ で持つ

**Comment by chohey** [comment]
- ローラースケート
    - bicycle, gear, gears
- 持てる爆弾を増やせるやつ
    - bomb, share-alt-square
- 投げられる奴
    - hand-paper-o
- 壁すり抜けられる奴
    - sign-in, sliders, navicon
- けれる奴
    - futbol-o, soccer-ball-o
- 威力増減するやつ
    - bolt, flash
